CREATE TABLE `queue_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniqid` varchar(32) NOT NULL,
  `type` int(11) NOT NULL DEFAULT '1',
  `parent_id` varchar(32) DEFAULT NULL,
  `subtasks_quantity` int(11) NOT NULL DEFAULT '0',
  `subtasks_quantity_not_performed` int(11) NOT NULL DEFAULT '0',
  `subtasks_error` int(11) NOT NULL DEFAULT '0',
  `exclusive` tinyint(1) NOT NULL DEFAULT '1',
  `task_group_id` int(11) DEFAULT '1',
  `task_name` varchar(255) NOT NULL,
  `status` tinyint(3) NOT NULL,
  `performer` varchar(45) DEFAULT NULL,
  `request_data` longtext,
  `response_data` longtext,
  `execution_date` DATETIME DEFAULT NULL,
  `callback` varchar(255) DEFAULT NULL,
  `error_callback` varchar(255) DEFAULT NULL,
  `settings` text,
  `priority` int(11) DEFAULT NULL,
  `create_date` datetime NOT NULL,
  `start_date` datetime DEFAULT NULL,
  `done_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`,`uniqid`),
  UNIQUE KEY `uniqid_UNIQUE` (`uniqid`),
  KEY `status` (`status`),
  KEY `fk_queue_tasks_1_idx1` (`parent_id`),
  KEY `fk_queue_tasks_1_idx` (`uniqid`),
  KEY `task_name` (`task_name`),
  KEY `type` (`type`),
  CONSTRAINT `fk_queue_tasks_1` FOREIGN KEY (`parent_id`) REFERENCES `queue_tasks` (`uniqid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
